FROM docker.grammatech.com/rewriting/gtirb/ubuntu18-gcc7

RUN apt-get install -y python3-pip && \
    python3 -m pip install --upgrade setuptools wheel

RUN cd /tmp && \
    git clone https://github.com/keystone-engine/keystone.git && \
    cd keystone && \
    mkdir build && \
    cd build && \
    ../make-share.sh && \
    make install
